# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1f5YZ9kxzIFvViEP3wEDLDwBYoc_Sp43G
"""

#pip install flask

from flask import Flask, request, jsonify
import pandas as pd
import numpy as np

# Assuming the following scripts are in the same directory
import collaborate_filtering
import hybrid_recsys
import content_based

app = Flask(__name__)

@app.route('/recommend', methods=['POST'])
def recommend():
    data = request.json
    user_id = data.get('user_id')
    fav_food = data.get('fav_food')
    cannot_eat = data.get('cant_eat')

    # 사용자 입력 받기
    user_id = 1
    cant_eat = "야채, 두부"
    fav_food = "새우, 닭발"

    user_profile = {
        "user_id": int(user_id),
        "cant_eat": cant_eat,
        "fav_food": fav_food
    }

    if not user_id or not fav_food or not cannot_eat:
        return jsonify({'error': 'Missing required parameters'}), 400

    try:
        # Here you should call your hybrid recommendation model
        recommended_market_ids = hybrid_recsys.get_recommendations(user_profile)
        return jsonify({'market_ids': recommended_market_ids})
    except Exception as e:
        return jsonify({'error': str(e)}), 500

if __name__ == '__main__':
    app.run(debug=True)