# -*- coding: utf-8 -*-
"""hybrid_recsys.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12Ir2YDT3tYNY8tdI2jKmGt26CDlZ4HoY
"""

import sys
import pandas as pd
import numpy as np
from sklearn.preprocessing import LabelEncoder, MultiLabelBinarizer
from sklearn.metrics.pairwise import cosine_similarity

# 파일에서 함수 불러오기
import content_based
import collaborate_filtering

#market_path = "/content/drive/MyDrive/Colab Notebooks/voiceFinder/recsys/notebooks/markets.csv"
market_path = "./markets.csv"

market_data = pd.read_csv(market_path)
market_data['market_id'] = market_data['market_id'].astype(int)

# 하이브리드 추천 시스템
def get_recommendations(user_profile, alpha=0.5):
    user_id = user_profile['user_id']

    cb_recommendation = content_based.get_recommendations(user_profile)
    cf_recommendation = collaborate_filtering.get_recommendations(user_id)

    combined_recommendation = alpha * cb_recommendation + (1 - alpha) * cf_recommendation

    top_recommendations = combined_recommendation.sort_values(ascending=False).head(3)

    return market_data[market_data['market_id'].isin(top_recommendations.index)]['market_id']

